# model_config.yaml

sample_rate: 16000
num_mel_bins: 80

encoder:
  type: conformer
  input_dim: 80
  d_model: 256
  num_layers: 6
  num_heads: 4
  dropout: 0.1

decoder:
  type: transformer
  d_model: 256
  num_layers: 4
  num_heads: 4
  dropout: 0.1

speaker_embedding:
  dim: 256
  loss: contrastive

asr_head:
  vocab_size: 5000  # tokenizer vocab size
  loss: ctc         # or "att"

slidar_head:
  enabled: true
  use_overlap: true
